config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users, :only => :show
    resources :questions do
      get :mark_as_spam, :on => :member
      get :subscribe, :on => :member
      collection do
        get :autocomplete
      end
      resources :answers
    end

    resources :answers do
      get :mark_as_spam, :on => :member
      get :like, :on => :member
      get :vote_down, :on => :member
      get :vote_up, :on => :member
    end

    namespace :admin do
      get :change_spam_level, to: "base#change_spam_level"
      resources :users, :only => :show do
        get :block, on: :member
        get :unblock, on: :member
      end
      root :to => "base#index"
    end
    get :search, to: 'questions#search'
    root 'base#index'
  end

  get "*path", to: redirect("/#{I18n.locale}/%{path}")
  get "", to: redirect("/#{I18n.locale}")
end

app/models/answer.rb
# -*- encoding : utf-8 -*-
class Answer < ActiveRecord::Base
  include MClaimable
  include MBlockable
  include MLikeable
  mount_uploader :map, MapUploader

  belongs_to :question, inverse_of: :answers
  belongs_to :user, inverse_of: :answers
  alias_attribute :author, :user
  has_many :claims, as: :claimable
  has_one :block, as: :blockable
  has_many :votes, as: :votable

  validates :body, :presence => true

  scope :active, -> { where(deleted: false).not_blocked.order(created_at: :desc) }
  scope :with_active_questions, -> { active.includes(:question).where(deleted: false, blocked:false)}
  scope :blocked, -> { joins(:block).where("blocks.blockable_id = id and blocks.blockable_type = 'Answer'") }

  def votes_count
    votes.up.size - votes.down.size
  end

  def voted_down_by?(user)
    user.votes.merge(self.votes.down).length > 0
  end

  def voted_up_by?(user)
    user.votes.merge(self.votes.up).length > 0
  end
end

app/controllers/answers_controller.rb
# -*- encoding : utf-8 -*-
class AnswersController < ApplicationController
  include CLikeable
  before_filter :find_question, except: [:destroy]
  before_filter :find_answer, except: [:create]

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    if @answer.save
      Notification::QuestionAnswered.new(answer: @answer).run
      flash[:notice] = t 'answers.created'
      redirect_to @answer.question
    else
      flash[:alert] = t 'answers.not_created'
      redirect_to :back
    end
  end

  def edit
    if current_user!= @answer.user
      flash[:alert]=t('errors.no_access')
      redirect_to @question
    end
  end

  def update
    if @answer.update(answer_params)
      flash[:notice] = t('answers.updated')
      redirect_to @question
    else
      flash[:alert] = t('answers.not_updated')
      render "edit"
    end
  end

  def destroy
    if current_user== @answer.user
      @answer.deleted=true
      @answer.save
      flash[:notice] = t('answers.deleted')
    else
      flash[:alert]=t('errors.no_access')
    end
    redirect_to :back
  end

  def mark_as_spam
    if @answer.claimed_by?(current_user)
      flash[:alert]=t 'spammed'
    else
      @question.create_claim_by(current_user)
      flash[:notice]=t('spammed')
    end
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  def like
    if @answer.user==current_user
      flash[:alert]=t('answers.errors.author_vote')
    else
      if @answer.liked_by?(current_user)
        dislike_it
      else
        like_it
      end
    end
    redirect_to :back
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  def vote_up
    if @answer.user==current_user
      flash[:alert]=t('answers.errors.author_vote')
    else
      if @answer.voted_up_by?(current_user)
        # unvote it
        @answer.votes.where(user: current_user, positive: true).destroy_all
      else
        # vote it up
        @answer.votes.where(user: current_user, positive: false).destroy_all
        @answer.votes.create(user: current_user, positive: true)
      end
    end
    respond_to do |f|
      f.js { render layout: false }
    end
  end

  def vote_down
    if @answer.user==current_user
      flash[:alert]=t('answers.errors.author_vote')
    else
      if @answer.voted_down_by?(current_user)
        # unvote it
        @answer.votes.where(user: current_user, positive: false).destroy_all
      else
        # vote it down
        @answer.votes.where(user: current_user, positive: true).destroy_all
        @answer.votes.create(user: current_user, positive: false)
      end
    end
    respond_to do |f|
      f.js { render layout: false }
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :map, :question_id, :map, :remote_map_url, :map_cache)
  end

  def find_question
    if params[:question_id]
      @question = Question.find(params[:question_id])
    else
      find_answer
      @question = @answer.question
    end
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/views/answers/_answer.html.erb
<div id="answer_<%= answer.id %>" class="answer">
  <%= distance_of_time_in_words_to_now(answer.created_at) %>
  <%= link_to answer.user.name, user_path(answer.user) %>
  <% admins_only do
    block_user_link(answer.user)
         end %>
  <%= answer.body %>
  <% if user_signed_in? %>

      <% if current_user==answer.user %>
          | <%= link_to t('answers.edit_link'), edit_answer_path(answer), {class: "editAnswerLink", id: "edit_#{answer.id}"} %>
          | <%= link_to t('answers.delete_link'), answer_path(answer), {method: :delete, data: {confirm: t('answers.confirm')}, class: "deleteAnswerLink", id: "delete_#{answer.id}"} %>

      <% else %>

          <% if @disliked_answers.include?(answer.id) %>
              | <span><%= t('spammed') %></span>
          <% else %>
              <% if answer.user!=current_user %>
                  | <%= link_to t('spam'), mark_as_spam_answer_path(answer) %>
              <% end %>
          <% end %>
      <% end %>
      <span class="answerLike">
      <% if @liked_answers.include?(answer.id) %>
          | <%= link_to t('answers.liked'), like_answer_path(answer) %>
      <% else %>
          | <%= link_to t('answers.like'), like_answer_path(answer) %>
      <% end %>

        <% if answer.lovers_count > 0 %>
          | <span class="likesCount"> <%= answer.lovers_count %> </span>
      <% end %>
          </span>
  <% end %>
</div>

app/views/answers/edit.html.erb
<h4><%= t('.title')%></h4>
<div id="answerForm">
  <%= render :partial => 'answers/form' %>
</div>

app/views/answers/vote_down.js.haml
- js = j cell(:answer, @answer).(:vote_block)
$('#vote_block_#{@answer.id}').html("#{js}");

app/views/answers/vote_up.js.haml
- js = j cell(:answer, @answer).(:vote_block)
$('#vote_block_#{@answer.id}').html("#{js}");