config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users, :only => :show
    resources :questions do
      get :mark_as_spam, :on => :member
      get :subscribe, :on => :member
      collection do
        get :autocomplete
      end
      resources :answers
    end

    resources :answers do
      get :mark_as_spam, :on => :member
      get :like, :on => :member
      get :vote_down, :on => :member
      get :vote_up, :on => :member
    end

    namespace :admin do
      get :change_spam_level, to: "base#change_spam_level"
      resources :users, :only => :show do
        get :block, on: :member
        get :unblock, on: :member
      end
      root :to => "base#index"
    end
    get :search, to: 'questions#search'
    root 'base#index'
  end

  get "*path", to: redirect("/#{I18n.locale}/%{path}")
  get "", to: redirect("/#{I18n.locale}")
end

app/controllers/admin/base_controller.rb
# -*- encoding : utf-8 -*-
class Admin::BaseController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @spam_level=Setting.spam_level
    @blocked_users=User.blocked
    @claimed_questions = Question.claimed
    @claimed_answer = Answer.claimed
  end

  def change_spam_level
    if params[:spam_level]
      Setting.spam_level = params[:spam_level]
    end
    redirect_to :index
  end
end

app/views/admin/base/_answer.html.erb
<div class="badAnswer" id="badAnswer_<%= answer.id %>">
  <%= answer.spam_counter %>
  | <%= link_to answer.user.name, admin_user_path(answer.user) %>
  | <%= link_to answer.body, question_path(answer.question) %>
  | <%= "Заблокирован." if answer.blocked? %>
</div>

app/views/admin/base/_question.html.erb
<div class="badQuestion" id="badQuestion_<%= question.id %>">
  <%= question.claims_count %>
  | <%= link_to question.user.name, admin_user_path(question.user) %>
  | <%= link_to question.body, question_path(question) %>
</div>

app/views/admin/base/_user.html.erb
<div class="badUser" id="badUser_<%= user.id %>">
   <%= user.block.created_at.stamp("31 mar'99 20:37") %>
  | <%= link_to user.name, admin_user_path(user) %>
</div>

app/views/admin/base/index.html.erb
<%= form_tag admin_change_spam_level_path, :method => :get do %>
    <p>
      <%= text_field_tag :spam_level, @spam_level %>
      <%= submit_tag "Сохранить", id: "submit" %>
    </p>
<% end %>

<h4>Заблокированные пользователи:</h4>
<%= render partial: 'admin/base/user', collection: @blocked_users %>
<h4>Помеченные вопросы:</h4>
<%= render partial: 'admin/base/question', collection: @claimed_questions %>
<h4>Помеченные ответы:</h4>
<%= render partial: 'admin/base/answer', collection: @claimed_answers %>