config/routes.rb
Rails.application.routes.draw do

  scope ":locale", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users, :only => :show
    resources :questions do
      get :mark_as_spam, :on => :member
      get :subscribe, :on => :member
      collection do
        get :autocomplete
      end
      resources :answers
    end

    resources :answers do
      get :mark_as_spam, :on => :member
      get :like, :on => :member
      get :vote_down, :on => :member
      get :vote_up, :on => :member
    end

    namespace :admin do
      get :change_spam_level, to: "base#change_spam_level"
      resources :users, :only => :show do
        get :block, on: :member
        get :unblock, on: :member
      end
      root :to => "base#index"
    end
    get :search, to: 'questions#search'
    root 'base#index'
  end

  get "*path", to: redirect("/#{I18n.locale}/%{path}")
  get "", to: redirect("/#{I18n.locale}")
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Finder
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = yield :javascript_includes
    :javascript
      $(function () {
          var questions = new Bloodhound({
              datumTokenizer: Bloodhound.tokenizers.obj.whitespace('body'),
              queryTokenizer: Bloodhound.tokenizers.whitespace,
              remote: { url: '/#{params[:locale]}/questions/autocomplete?query=%QUERY',
                  wildcard: '%QUERY'}
          });

          $('#search .typeahead').typeahead(null, {
              name: 'questions',
              display: 'body',
              source: questions,
              templates: {
                  empty: [
                      '<div class="empty-message">',
                      '#{t("search.empty")}',
                      '</div>'
                  ].join('\n'),
                  suggestion: Handlebars.compile('<div><a href=/questions/></a></div>')
              }

          });
          $('.modalable').click(function(e){
            e.preventDefault();
            $('.small.modal').modal('show');
          });
          $('.ui.dropdown').dropdown();
          $('.sticky').sticky({ context: '#context' });
      });
    = csrf_meta_tags
  %body{ style: 'display: flex; min-height: 100vh; flex-direction: column;'}
    .full-height{style: 'flex: 1;'}
      .ui.sixteen.wide.column.doubling.relaxed.grid.container
        .row{style: 'padding-top: 20px;'}
          .three.wide.column
            .h1.ui.header.centered{style: 'font-size: 35px;'}
              = link_to 'Finder', root_path, {class: 'item'}
          .nine.wide.column
            = form_tag search_path, class: 'ui form', :method => :get, remote: true do
              .field
                = text_field_tag :query, params[:query], {class: 'typeahead', placeholder: t('base.index.search')}
          .one.wide.column
            = link_to url_for( :locale => 'ru' ) do
              %i.ru.flag
            = link_to url_for( :locale => 'en' ) do
              %i.gb.flag
          .three.wide.column
            = link_to t('add_question'), new_question_path(I18n.locale), {class: "ui green basic button #{@restrict}"}

        .row
          .three.wide.column
            .ui.vertical.menu
              - if user_signed_in?
                .item
                  = image_tag current_user.avatar.thumb.url, class: 'ui avatar image'
                  %span= link_to current_user.name, user_path(current_user)
                .menu
                  - admins_only do
                    = link_to "Admin panel", admin_root_path, class: 'item'
                  = link_to t('devise.shared.links.sign_out'), destroy_user_session_path, method: :delete, class: 'item'
              - else
                = link_to t('devise.shared.links.sign_in'), new_user_session_path, class: 'item'
              - if user_signed_in?
                %a.active.item Моя лента
              = link_to 'Все вопросы', root_path, {class: 'item'}
              %a.item Пользователи
              - if user_signed_in?
                %a.item Уведомления
          .ten.wide.column
            .ui.main.text.container{style: "padding-left: 20px;", id: 'context'}
              - flash.each do |key, value|
                %div{:class => "ui #{key} message flash"}
                  %i.close.icon
                  %p= value
              = yield
          .three.wide.column
      .ui.small.modal
        %i.close.icon
        .content
          = render file: 'devise/sessions/new'
    .ui.black.inverted.vertical.footer.segment
      .ui.center.aligned.container
        .ui.stackable.inverted.grid
          .three.wide.column
            %h4.ui.inverted.header Community
            .ui.inverted.link.list
              %a.item{:href => "https://www.transifex.com/organization/semantic-org/", :target => "_blank"} Help Translate
              %a.item{:href => "https://github.com/Semantic-Org/Semantic-UI/issues", :target => "_blank"} Submit an Issue
              %a.item{:href => "https://gitter.im/Semantic-Org/Semantic-UI", :target => "_blank"} Join our Chat
              %a.item{:href => "/cla.html", :target => "_blank"} CLA

app/views/layouts/application_template.haml
!!!
%html
  %head
    %title Finder
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = yield :javascript_includes
    :javascript
      $(function () {
          var questions = new Bloodhound({
              datumTokenizer: Bloodhound.tokenizers.obj.whitespace('body'),
              queryTokenizer: Bloodhound.tokenizers.whitespace,
              remote: { url: '/#{params[:locale]}/questions/autocomplete?query=%QUERY',
                  wildcard: '%QUERY'}
          });

          $('#search .typeahead').typeahead(null, {
              name: 'questions',
              display: 'body',
              source: questions,
              templates: {
                  empty: [
                      '<div class="empty-message">',
                      '#{t("search.empty")}',
                      '</div>'
                  ].join('\n'),
                  suggestion: Handlebars.compile('<div><a href=/questions/></a></div>')
              }

          });
      });
    :javascript
      $(function () {
          // create sidebar and attach to menu open
          $('.ui.sidebar').sidebar('attach events', '.toc.item');
          $('.ui.dropdown').dropdown();
      });
    = csrf_meta_tags
  %body
    .ui.vertical.inverted.sidebar.menu{id: "toc"}>
      %a.active.item Home
      %a.item Work
      %a.item Company
      %a.item Careers
      %a.item Login
      %a.item Signup
    / Page Contents
    .pusher
      .full-height
        .toc
          .ui.secondary.menu
            .ui.container
              %a.toc.item
                %i.sidebar.icon
              = link_to 'Finder', root_path, {class: 'item'}
              .ui.category.search.item
                = form_tag search_path, :method => :get, remote: true do
                  .ui.transparent.icon.input
                    = text_field_tag :query, params[:query], {class: 'typeahead', placeholder: t('base.index.search')}
                    %i.search.link.icon
                  .results
              .right.menu
                .item
                  = link_to t('add_question'), new_question_path(I18n.locale), {class: 'ui green basic button'}
                .item
                  = link_to url_for( :locale => 'ru' ) do
                    %i.ru.flag
                  = link_to url_for( :locale => 'en' ) do
                    %i.gb.flag
          %nav
            - if current_user
              - admins_only do
                = link_to "Admin", admin_root_path
              = t('users.logined') and link_to "[#{current_user.name}]", user_path(current_user)
              = link_to t('devise.shared.links.sign_out'), destroy_user_session_path, method: :delete
            - else
              = link_to t('devise.shared.links.sign_in'), new_user_session_path
              = link_to t('devise.shared.links.sign_up'), new_user_registration_path
          - flash.each do |key, value|
            %div{:class => "ui #{key} message flash"}
              %i.close.icon
              %p= value
          .ui.main.text.container
            = yield
          .ui.divider